### ISSUE TITLE
Bug Report for HexaEcon Plugin (Version: Jun 24, 2024)

### ISSUE THREAD

**Issue by var1nthon** [OwOFuFu/HexaEcon#1]
The bug is related to the HexaEcon plugin failing to load due to a missing main class. The error message indicates that the dev.unstackss.hexaecon.HexaEcon class cannot be found, resulting in a ClassNotFoundException and consequently causing the plugin to fail to load.

**Steps to Reproduce**
1. Place the HexaEcon.jar file in the plugins directory.
2. Start or restart the server.
3. Observe the server logs for the ClassNotFoundException error.

**Expected Behavior**
The HexaEcon plugin should load successfully without any errors, and its functionality should be available in the server.

**Actual Behavior**
The server log shows an InvalidPluginException due to the main class dev.unstackss.hexaecon.HexaEcon not being found, which prevents the HexaEcon plugin from loading.

**Server Environment**
Minecraft version: 1.21
HexaEcon plugin version: HexaEcon - Economy System 1.8-1.21
Date: UnStacks, Jun 24, 2024
Server type: Paper
My log: https://paste.helpch.at/amamecayer.makefile

**Additional Information**
Ensure that the HexaEcon.jar file is correctly placed in the plugins directory.
Verify that the plugin.yml file inside the HexaEcon.jar specifies the correct main class path (dev.unstackss.hexaecon.HexaEcon).
Check if the main class HexaEcon is correctly located in the dev.unstackss.hexaecon package within the HexaEcon.jar file.

**Comment by UnStackss** [comment]
Fixed 👍🏻 and thanks for the Issue
https://www.spigotmc.org/resources/hexaecon-economy-system-%E2%9C%A8.109871/

**Comment by StrayVibes** [comment]
Fixed 👍🏻 and thanks for the Issue
https://www.spigotmc.org/resources/hexaecon-economy-system-%E2%9C%A8.109871/
